<a href="https://colab.research.google.com/github/EricFlores1808/MINERIA_EF_LS_1/blob/luis_desarrollo/SocialMediaImpact.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [10]:
df = pd.read_csv("/content/Teen_Mental_Health_Dataset.csv")

In [11]:
df.columns

#En este Dataset podemos encontrar diversas columnas tanto categorias como: Gender, Plataform_usage y Social_interaction_level
#Al igual que podemos encontrar columnas numericas como: age, daily_social_media_hours, sleep_hours, screen_time_before_sleep, academic_performance, physical_activity,
#stress_level, anxiety_level, addiction_level y depression_label.

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label'],
      dtype='object')

In [12]:
df.shape

#Contamos con 13 columnas donde 3 son categoricas y 10 numericas
#tenemos 1200 filas para trabajar

(1200, 13)

In [20]:
df.isna().sum()

#Este Dataset no cuenta con valores nulos, por lo tanto no necesita ser limpiado para trabajarlo

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

In [13]:
df.head()

#Aca podemos ver un ejemplo de los formatos que encontraremos de los datos

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [16]:
df.info()

#Aca podemos ver una informacion mas detallada de las columnas que tenemos con la cantidad de filas con las que cuentan y
#si existen datos nulos ademas de decir que tipo de dato es

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), object(3)
memory usage: 122.0+ KB

In [18]:
df.describe().round()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.0,1200.0,1200.0,1200.0,1200.0,1200.0,1200.0,1200.0,1200.0,1200.0
mean,16.0,5.0,6.0,2.0,3.0,1.0,5.0,6.0,6.0,0.0
std,2.0,2.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,0.0
min,13.0,1.0,4.0,0.0,2.0,0.0,1.0,1.0,1.0,0.0
25%,14.0,3.0,5.0,1.0,2.0,0.0,3.0,3.0,3.0,0.0
50%,16.0,4.0,6.0,2.0,3.0,1.0,5.0,6.0,6.0,0.0
75%,18.0,6.0,8.0,2.0,3.0,2.0,8.0,8.0,8.0,0.0
max,19.0,8.0,9.0,3.0,4.0,2.0,10.0,10.0,10.0,1.0